version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fpm
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    environment:
      - PHP_FPM_LISTEN=9000

  php-fpm:
    build:
      context: ./backend
      dockerfile: Dockerfile.fpm
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - php-fpm

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

  db:
    image: mariadb:10.5
    container_name: mariadb_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
